# Generated by Django 5.0.7 on 2024-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_staff_registration_user_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_registration',
            name='offer_letter',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
