# Generated by Django 5.0.7 on 2024-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_staff_registration_offer_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_registration',
            old_name='offer_letter',
            new_name='id_card',
        ),
        migrations.AddField(
            model_name='user_registration',
            name='id_card',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
